### ISSUE TITLE
Does a Permitted Purpose supersede a Competing Use?

### ISSUE THREAD

**Issue by ezekg** [getsentry/fsl.software#13] opened 2023-11-17 15:34 UTC
Digging into the license text last night and noticed something ambiguous. From the license text:

> ### Permitted Purpose
> 
> A Permitted Purpose is any purpose other than a Competing Use. A Competing Use
> means use of the Software in or for a commercial product or service that
> competes with the Software or any other product or service we offer using the
> Software as of the date we make the Software available.
> 
> Competing Uses specifically include using the Software:
> 
> 1. as a substitute for any of our products or services;
> 
> 2. in a way that exposes the APIs of the Software; and
> 
> 3. in a product or service that offers the same or substantially similar
> functionality to the Software.
> 
> Permitted Purposes specifically include using the Software:
> 
> 1. for your internal use and access;
> 
> 2. for non-commercial education;
> 
> 3. for non-commercial research; and
> 
> 4. in connection with software development services or managed services that
> you provide to a licensee using the Software in accordance with these Terms and
> Conditions.

At a cursory glance, this makes it seem like you can't self-host the Software for internal use because although it's a Permitted Purpose under 1, it is also a Competing Use under 1 and 2. And "a Permitted Purpose is any purpose _other than_ a Competing Use" (emphasis mine) makes it seem like all Competing Uses supersede Permitted Purposes (i.e. the "other than" verbiage).

Can the text be clarified? I'd assume you want Permitted Purposes 1-4 to supersede Competing Uses 1-3 to allow self-hosting in a non-competing way before the Change License takes effect.

**Comment by chadwhitacre** [comment] 2023-11-17 22:37
cc: @gavin-zee @hmeeker

**Comment by gavin-zee** [comment] 2023-11-17 22:49
Certainly not the intent. The list of Competing Uses are intended to provide examples of competing commercial products or services, not as restrictions on internal use.

**Comment by ThiefMaster** [comment] 2023-11-18 16:34
Assuming points 1-3 in Competing Uses are individual examples and not "if you do 1, 2 and 3", then how does this sentence *not* exclude self-hosting in order to not having to pay for the software?

> Competing Uses specifically include using the Software as a substitute for any of our products or services

Clearly you are substituting the commercial SaaS product with your free on-prem setup. So I'm really curious how (especially when just taking the legalese into account, because I think no lawyer will accept "oh, but on GitHub they say it's OK" in addition to the actual license text) the license allows this :).

**Comment by ThiefMaster** [comment] 2023-11-18 16:38
Another question is on the definition of "for your internal use and access". If you are a normal company "internal" is quite clear: You use it within the company (e.g. in case of Sentry to monitor your own software or service).

But let's take another example: What if you are an international collaboration (which is quite common in the research sector). Can you run an onprem Sentry instance that is available for members of that collaboration? The people using it are affiliated with it in some way, but not necessarily direct employees. So can "internal" be understood as "not the general public"?

**Comment by gavin-zee** [comment] 2023-11-18 16:56
> Another question is on the definition of "for your internal use and access". If you are a normal company "internal" is quite clear: You use it within the company (e.g. in case of Sentry to monitor your own software or service).
> 
> But let's take another example: What if you are an international collaboration (which is quite common in the research sector). Can you run an onprem Sentry instance that is available for members of that collaboration? The people using it are affiliated with it in some way, but not necessarily direct employees. So can "internal" be understood as "not the general public"?

We wanted to list a few specific use cases we most frequently get questions about as examples of permitted purposes. That list is not intended to be dispositive by any means. The collaboration you've described does not sound like it would involve offering a competing commercial product or service , therefore would be a permitted purpose as well.

**Comment by chadwhitacre** [comment] 2023-11-20 22:26
Is there a clarification needed in the license text here? Or do we think it's enough to have this thread documenting the interpretation?

**Comment by heathermeeker** [comment] 2023-11-21 00:48
So, the issue is that we are concerned that an internal use is a substitute? I don't think those can overlap, because I view substitute as an economic term. I don't see how any internal use could be a substitute in the market, because the user is not selling into any market. But if others disagree, it could be revised--or just handle in meta information. We are balancing plain language against clarity, and it will always be imperfect.

**Comment by ljharb** [comment] 2023-11-21 01:41
If the user is using it internally in place of purchasing an external solution from the licensor, is that use permitted or not?

**Comment by gavin-zee** [comment] 2023-11-21 02:02
> If the user is using it internally in place of purchasing an external solution from the licensor, is that use permitted or not?

Yes, definitely a permitted use.

**Comment by ljharb** [comment] 2023-11-21 02:05
What if the user is advertising or recommending to others that anyone who needs to use it internally does so following a guide they provide? Still permitted?

**Comment by ezekg** [comment] 2023-11-26 05:21
I still feel like the license text is ambiguous. It presents permitted uses that are also competing uses. Some text to clearly state that competing uses must meet a set of criteria would be helpful because right now, a permitted use is anything that is not a competing use but a competing use is a wide ambiguous net when it comes to self-hosting. Or you could use wording like "the following are considered permitted uses and are not competing uses: 1. for your internal use..."

The problem stems from this sentence:

> A Permitted Purpose is any purpose other than a Competing Use.

This says a permitted use cannot also be a competing use. And competing uses 1-2 specifically cover self-hosting an API, so self-hosting falls into the land of ambiguity.

**Comment by chadwhitacre** [comment] 2024-02-09 22:31
PR is up in #32 for FSL-1.1. Here's [where we're at](https://github.com/getsentry/fsl.software/pull/32/commits/2cb1c0feefca1847073393c185512ae7ed2532dd?short_path=5008c97#diff-5008c97c0d6897c7b205424f12a6588d5ffdecd69ea3760e8c3b4c2eab77dd38) to address the current issue:

> A Permitted Purpose is any purpose other than a Competing Use. A Competing Use means making the Software available to others in a commercial product or service that:
>
> 1. substitutes for any of our products or services; or
> 1. offers the same or substantially similar functionality as the Software; or
> 1. otherwise competes with the Software or any other product or service we offer using the Software as of the date we make the Software available.

<img width="1005" alt="Screenshot 2024-02-09 at 5 28 34 PM" src="https://github.com/getsentry/fsl.software/assets/134455/bcb7a9b2-cb1c-4419-b867-eb0ad2bbd0da">

**Comment by chadwhitacre** [comment] 2024-02-09 22:31
Does that work for you @ezekg?

**Comment by mon-jai** [comment] 2024-02-10 17:43
@chadwhitacre A dumb question: did the license reviewed by lawyers?

**Comment by chadwhitacre** [comment] 2024-02-12 13:35
@mon-jai There's no such thing as a dumb question! :-)

> did the license reviewed by lawyers?

Yes, @gavin-zee and @hmeeker are both lawyers. The three of us had a call on Friday where we went through the open issues on #23 and worked on updating the license text.

**Comment by ezekg** [comment] 2024-02-12 21:54
@chadwhitacre I think it's much clearer now that the "competing uses specifically include using the software" line was removed. Now it reads like "these are competing uses, which are not allowed, but these specific permitted purposes are specifically (always) allowed", which is what I think you were aiming for.

**Comment by chadwhitacre** [comment] 2024-02-14 22:32
Okay I think we're good here? Closing this out and moving forward on #32. Lmk if we need to reopen.

Thanks! 🙌

**Closed by chadwhitacre** 2024-02-14 22:32 UTC
Labels: clarification
